package com.example.llmagentsystem.repository;

import com.example.llmagentsystem.model.entity.TaskEntity;
import com.example.llmagentsystem.model.entity.TaskHistoryEntity;
import com.example.llmagentsystem.model.entity.UserEntity;
import com.example.llmagentsystem.model.enums.TaskStatus; // For creating TaskEntity
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
class TaskHistoryRepositoryIntegrationTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private TaskHistoryRepository taskHistoryRepository;

    @Autowired
    private UserRepository userRepository; // For creating UserEntity

    @Autowired
    private TaskRepository taskRepository; // For creating TaskEntity

    private UserEntity testUser;
    private TaskEntity testTask;
    private ObjectMapper objectMapper;


    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());

        testUser = new UserEntity();
        testUser.setPlatformId("historyTestUser");
        testUser.setSourcePlatform("test");
        testUser.setEmail("historyTestUser@example.com"); // Ensure unique email
        userRepository.save(testUser);

        UserEntity creator = new UserEntity(); // Task needs a creator
        creator.setPlatformId("taskCreatorForHistory");
        creator.setSourcePlatform("test");
        creator.setEmail("taskCreatorForHistory@example.com"); // Ensure unique email
        userRepository.save(creator);

        entityManager.flush(); // Ensure users are persisted

        testTask = new TaskEntity();
        testTask.setDescription("Task for history test");
        testTask.setCreator(creator); // Set the persisted creator
        testTask.setStatus(TaskStatus.PENDING);
        taskRepository.save(testTask);

        entityManager.flush(); // Ensure task is persisted
    }

    private TaskHistoryEntity createAndPersistHistory(TaskEntity task, UserEntity user, String eventType, Map<String, String> details, OffsetDateTime timestamp)
            throws JsonProcessingException {
        TaskHistoryEntity history = new TaskHistoryEntity();
        history.setTask(task);
        history.setUserWhoChanged(user);
        history.setEventType(eventType);
        history.setChangeDetails(objectMapper.writeValueAsString(details));
        history.setTimestamp(timestamp); // Set timestamp explicitly for ordering tests
        return entityManager.persistFlushFind(history);
    }

    @Test
    void whenSaveTaskHistory_thenFindById_returnsTaskHistory() throws JsonProcessingException {
        TaskHistoryEntity newHistory = new TaskHistoryEntity();
        newHistory.setTask(testTask);
        newHistory.setUserWhoChanged(testUser);
        newHistory.setEventType("STATUS_CHANGED");
        Map<String, String> details = Map.of("old_status", "PENDING", "new_status", "IN_PROGRESS");
        newHistory.setChangeDetails(objectMapper.writeValueAsString(details));
        // Timestamp is auto-generated by @CreationTimestamp on entity if not set,
        // but for testing order, setting it can be useful. Here, rely on default if not explicitly set.
        // For this test, let's set it to ensure the value we check is the one we set or default.
        // If relying on @CreationTimestamp, then just check for not-null.
        newHistory.setTimestamp(OffsetDateTime.now());


        TaskHistoryEntity savedHistory = taskHistoryRepository.save(newHistory);
        entityManager.flush();
        entityManager.clear();

        Optional<TaskHistoryEntity> foundOpt = taskHistoryRepository.findById(savedHistory.getHistoryId());

        assertThat(foundOpt).isPresent();
        TaskHistoryEntity found = foundOpt.get();
        assertThat(found.getEventType()).isEqualTo("STATUS_CHANGED");
        assertThat(found.getTask().getTaskId()).isEqualTo(testTask.getTaskId());
        assertThat(found.getUserWhoChanged().getUserId()).isEqualTo(testUser.getUserId());
        assertThat(found.getChangeDetails()).isEqualTo(objectMapper.writeValueAsString(details));
        assertThat(found.getHistoryId()).isNotNull();
        assertThat(found.getTimestamp()).isNotNull(); // Check it's set
    }

    @Test
    void findByTaskTaskIdOrderByTimestampDesc_returnsHistoryInCorrectOrder() throws JsonProcessingException {
        OffsetDateTime now = OffsetDateTime.now();
        Map<String, String> details1 = Map.of("action", "commented");
        Map<String, String> details2 = Map.of("action", "updated description");
        Map<String, String> details3 = Map.of("action", "changed status");

        TaskHistoryEntity h1 = createAndPersistHistory(testTask, testUser, "COMMENT_ADDED", details1, now.minusMinutes(10));
        TaskHistoryEntity h2 = createAndPersistHistory(testTask, testUser, "DESCRIPTION_UPDATED", details2, now.minusMinutes(5));
        TaskHistoryEntity h3 = createAndPersistHistory(testTask, testUser, "STATUS_CHANGED", details3, now);

        // Create history for another task to ensure filtering by taskId
        TaskEntity otherTask = new TaskEntity();
        otherTask.setDescription("Another task");
        otherTask.setCreator(testTask.getCreator()); // Re-use creator
        otherTask.setStatus(TaskStatus.PENDING);
        taskRepository.save(otherTask);
        entityManager.flush();
        createAndPersistHistory(otherTask, testUser, "CREATED", Map.of("status", "PENDING"), now);


        List<TaskHistoryEntity> historyItems = taskHistoryRepository.findByTaskTaskIdOrderByTimestampDesc(testTask.getTaskId());

        assertThat(historyItems).hasSize(3);
        assertThat(historyItems.get(0).getHistoryId()).isEqualTo(h3.getHistoryId()); // Most recent
        assertThat(historyItems.get(0).getEventType()).isEqualTo("STATUS_CHANGED");
        assertThat(historyItems.get(1).getHistoryId()).isEqualTo(h2.getHistoryId());
        assertThat(historyItems.get(1).getEventType()).isEqualTo("DESCRIPTION_UPDATED");
        assertThat(historyItems.get(2).getHistoryId()).isEqualTo(h1.getHistoryId());
        assertThat(historyItems.get(2).getEventType()).isEqualTo("COMMENT_ADDED");
    }

    @Test
    void findByTaskTaskIdOrderByTimestampDesc_whenNoHistoryForTask_returnsEmptyList() {
        UUID nonExistentTaskId = UUID.randomUUID();
        List<TaskHistoryEntity> historyItems = taskHistoryRepository.findByTaskTaskIdOrderByTimestampDesc(nonExistentTaskId);
        assertThat(historyItems).isEmpty();
    }
}
